steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/civic-gate-353504/bima-image/wp:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/civic-gate-353504/bima-image/wp:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'wp-test'
    - '--image'
    - 'gcr.io/civic-gate-353504/bima-image/wp:$COMMIT_SHA'
    - '--region'
    - 'asia-southeast2'
    - '--platform'
    - 'managed'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '1'
    - '--allow-unauthenticated'
    - '--service-account'
    - 'sql-test-bima@civic-gate-353504.iam.gserviceaccount.com'
    - '--add-cloudsql-instances'
    - 'civic-gate-353504:asia-southeast2:privcoba'
    - '--vpc-connector'
    - 'vpc-con'

images:
- 'gcr.io/civic-gate-353504/bima-image/wp'
options:
  logging: CLOUD_LOGGING_ONLY
